name: Python app CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Build and deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: <app-name>
        slot-name: <slot-name>
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_<app-name> }}
